# .github/workflows/build.yml

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # 또는 빌드하고 싶은 브랜치 이름으로 변경
    paths:
      - "client/**" # client 디렉토리 하위 파일이 변경될 때만 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # 원하는 Node.js 버전으로 설정

      - name: Install and Build
        working-directory: ./client # client 디렉토리로 이동
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.MY_PERSONAL_TOKEN }}
          publish_dir: ./client/dist # 빌드된 파일이 위치한 디렉토리
